-- 코드를 입력하세요
SELECT CC.CAR_ID, CC.CAR_TYPE, FLOOR(CC.DAILY_FEE * 30 * (100 - (
    SELECT REPLACE(DISCOUNT_RATE, "%", "")
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    WHERE P.CAR_TYPE = CC.CAR_TYPE AND P.DURATION_TYPE LIKE '30일 이상'
)) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CC
WHERE (CC.CAR_TYPE LIKE '세단' OR CC.CAR_TYPE LIKE 'SUV') AND
    CC.CAR_ID NOT IN (
        SELECT DISTINCT C.CAR_ID
        FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
        WHERE (C.CAR_TYPE LIKE '세단' OR C.CAR_TYPE LIKE 'SUV') AND
            ((START_DATE < DATE("2022-11-01") AND END_DATE >= DATE("2022-11-01")) OR
            (START_DATE >= DATE("2022-11-01") AND START_DATE <= DATE("2022-11-30"))))
GROUP BY CC.CAR_ID
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CC.CAR_TYPE ASC, CC.CAR_ID DESC