-- 코드를 입력하세요
SELECT HISTORY_ID, FLOOR((DATEDIFF(END_DATE, START_DATE) + 1) * DAILY_FEE * (100 - (
    CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 7 THEN 0
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 AND DATEDIFF(END_DATE, START_DATE) + 1 < 30 THEN (
        SELECT REPLACE(DISCOUNT_RATE, "%", "")
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE CAR_TYPE LIKE "트럭" AND DURATION_TYPE LIKE "7%"
    )
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN (
        SELECT REPLACE(DISCOUNT_RATE, "%", "")
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE CAR_TYPE LIKE "트럭" AND DURATION_TYPE LIKE "90%"
    )
    ELSE (
        SELECT REPLACE(DISCOUNT_RATE, "%", "")
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE CAR_TYPE LIKE "트럭" AND DURATION_TYPE LIKE "30%"
    )
    END
)) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
WHERE CAR_TYPE LIKE "트럭"
ORDER BY FEE DESC, HISTORY_ID DESC