-- 코드를 작성해주세요
SELECT E.EMP_NO, EMP_NAME, (
    CASE WHEN SCORE >= 96 THEN 'S'
    WHEN SCORE >= 90 THEN 'A'
    WHEN SCORE >= 80 THEN 'B'
    ELSE 'C' END
) AS GRADE, SAL * (
    CASE WHEN SCORE >= 96 THEN 20
    WHEN SCORE >= 90 THEN 15
    WHEN SCORE >= 80 THEN 10
    ELSE 0 END
) / 100 AS BONUS
FROM HR_EMPLOYEES E JOIN (
    SELECT EMP_NO, AVG(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO, YEAR
) G ON E.EMP_NO = G.EMP_NO
ORDER BY E.EMP_NO