-- 코드를 작성해주세요
SELECT A.SCORE, A.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL
FROM (SELECT SUM(SCORE) AS SCORE, EMP_NO
    FROM HR_GRADE
    GROUP BY EMP_NO) A JOIN HR_EMPLOYEES B ON A.EMP_NO = B.EMP_NO
ORDER BY A.SCORE DESC
LIMIT 1