-- 코드를 작성해주세요
SELECT (
    CASE WHEN ((SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY LIKE "Front End") & SKILL_CODE > 0) AND 
            ((SELECT CODE FROM SKILLCODES WHERE NAME LIKE "Python") & SKILL_CODE > 0) THEN "A"
        WHEN ((SELECT CODE FROM SKILLCODES WHERE NAME LIKE "C#") & SKILL_CODE > 0) THEN "B"
        ELSE "C"
    END
) AS GRADE, ID, EMAIL
FROM DEVELOPERS
WHERE ((SELECT CODE FROM SKILLCODES WHERE NAME LIKE "C#") & SKILL_CODE > 0) OR 
    ((SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY LIKE "Front End") & SKILL_CODE > 0)
ORDER BY GRADE ASC, ID ASC